.PHONY: clean All

All:
	@echo "----------Building project:[ calloc - Debug ]----------"
	@cd "calloc" && "$(MAKE)" -f  "calloc.mk"
clean:
	@echo "----------Cleaning project:[ calloc - Debug ]----------"
	@cd "calloc" && "$(MAKE)" -f  "calloc.mk" clean
